CREATE TABLE IF NOT EXISTS eggs (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  species TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  hatch_at TIMESTAMP NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING'
);
CREATE INDEX IF NOT EXISTS idx_eggs_due ON eggs (status, hatch_at);
